In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_27892\80980253.py", line 1, in <module>
    import tensorflow as tf
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\client\pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\ipykernel\zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_27892\80980253.py", line 1, in <module>
    import tensorflow as tf
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 96, in <module>
    from tensorflow.python.data.experimental import service
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 24, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\data\util\structure.py", line 23, in <module>
    from tensorflow.python.data.util import nest
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\data\util\nest.py", line 36, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 24, in <module>
    from tensorflow.python.framework import constant_op
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\framework\constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\eager\execute.py", line 23, in <module>
    from tensorflow.python.framework import dtypes
  File "c:\Users\User\Documents\krish_projects\churn_project\venv\lib\site-packages\tensorflow\python\framework\dtypes.py", line 29, in <module>
    from tensorflow.python.lib.core import _pywrap_bfloat16

AttributeError: _ARRAY_API not found

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import

TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

In [ ]:
#Load the ANN trained model, scaler pickle, onehot pickle.
model = tf.keras.models.load_model("model.h5", compile=False)

# Load the encoder and scaler
with open ("onehot_encoder_geo.pkl","rb") as file:
    onehot_encoder_geo=pickle.load(file)

with open ("label_encoder_gender.pkl","rb") as file:
    label_encoder_gender=pickle.load(file)
    
with open ("scaler.pkl","rb") as file:
    scaler=pickle.load(file)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [ ]:
# Example input data
input_data={"CreditScore":600,
            "Geography":"France",
            "Gender":"Male",
            "Age":40,
            "Tenure":3,
            "Balance":60000,
            "NumOfProducts":2,
            "HasCrCard": 1,
            "IsActiveMember":1,
            "EstimatedSalary":50000
}

In [ ]:
# change this dictionary into data frame
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [ ]:
# Encode categorical variables
input_df["Gender"]=label_encoder_gender.transform(input_df["Gender"])
input_df["Gender"]

0    1
Name: Gender, dtype: int64

In [ ]:
# One hot encoding "Gepgraphy"
geo_encoder=onehot_encoder_geo.transform([[input_data["Geography"]]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))
geo_encoded_df

c:\Users\tharu\OneDrive\Desktop\VS_code_files\churn_project\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [ ]:
# Concatination one hot encode
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)

In [ ]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [ ]:
# Scaling the input data
input_scaled=scaler.transform(input_df)

In [ ]:
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step

array([[0.02723564]], dtype=float32)

In [ ]:
prediction_proba=prediction[0][0]
prediction_proba

np.float32(0.02723564)

In [ ]:
# 0.03<0.5 ,so customer is not likely to churn